name: Build Aseprite

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake ninja-build libx11-dev libxcursor-dev libxi-dev libgl1-mesa-dev libfontconfig1-dev
        sudo apt-get install -y libxrandr-dev libxinerama-dev libavutil-dev libavcodec-dev libavformat-dev libswscale-dev libfreetype6-dev
        sudo apt-get install -y libglew-dev libpng-dev libtiff5-dev libwebp-dev libjsoncpp-dev libssl-dev libcurl4-openssl-dev

    - name: Clone Aseprite
      run: |
        git clone --recursive https://github.com/aseprite/aseprite.git
        cd aseprite
        git checkout tags/v1.3.0

    - name: Build Aseprite
      run: |
        cd aseprite
        mkdir build && cd build
        cmake \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          -DLAF_OS_BACKEND=skia \
          -DSKIA_DIR=$HOME/skia \
          -G Ninja \
          ..
        ninja aseprite

    - name: Package Aseprite
      run: |
        cd aseprite/build
        mkdir package
        cp bin/aseprite package
        cp ../data/extensions/*.lua package
        zip -r aseprite.zip package/
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: aseprite
        path: aseprite/build/aseprite.zip
